/**
 * Canonical avatar seed resolver – single source of truth for all screens.
 *
 * Previously, each screen (today.tsx, choose.tsx, candidates.tsx, manage.tsx)
 * contained an inline copy of resolveAvatarSeed. Those copies lacked:
 *   - legacy URL extraction (old api.multiavatar.com/…svg format)
 *   - consistent normalisation (lowercase)
 *
 * This module replaces all of them.
 */
import { extractSeedFromLegacyUrl } from '../services/multiavatar';

/**
 * Deterministic fallback seed when only id + displayName are available.
 * Used when building MemberSnapshots without the member's own profile on-hand.
 */
export function fallbackAvatarSeed(id: string, displayName: string): string {
  return `${id}:${displayName}`.toLowerCase();
}

/**
 * Returns true if the given avatarUrl was generated by fallbackAvatarSeed
 * (i.e. it is NOT a user-chosen seed). Used in the backend push to avoid
 * overwriting a real seed with a stale generated fallback.
 */
export function isFallbackAvatarSeed(
  avatarUrl: string,
  id: string,
  displayName: string
): boolean {
  return avatarUrl === fallbackAvatarSeed(id, displayName);
}

/**
 * Canonical avatar seed resolver.
 *
 * Priority order (deterministic, cross-device safe):
 *   1. avatarUrl matches legacy API URL format
 *      → extract seed from URL (e.g. "Alice" from .../Alice.svg)
 *   2. avatarUrl is a clean seed (non-empty, non-URL)
 *      → use directly, lowercased
 *   3. No avatarUrl (empty / undefined)
 *      → fallbackAvatarSeed(id, displayName)
 *
 * Never returns an empty string when id or displayName are provided.
 */
export function resolveAvatarSeed(
  id: string,
  displayName: string,
  avatarUrl?: string
): string {
  const raw = avatarUrl?.trim();
  if (raw && raw.length > 0) {
    // Handle legacy https://api.multiavatar.com/<seed>.svg URLs
    const extracted = extractSeedFromLegacyUrl(raw);
    if (extracted) return extracted.toLowerCase();
    return raw.toLowerCase();
  }
  return fallbackAvatarSeed(id, displayName);
}
